services:
  - type: web
    name: creatoriq-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: MONGO_URL
        value: mongodb+srv://yashshaha999_db_user:MNeu9DCyR42Ycn57@cluster0.xswno2v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: SECRET_KEY
        value: super-secret-creatoriq-key-2026
